config/routes.rb
# rubocop:disable Metrics/BlockLength
require_relative 'subdomains'

Rails.application.routes.draw do
  scope '(:locale)', locale: /de|en/ do
    get 'automated_driving' => 'geo_scenes#show_on_map', id: 1

    root 'pages#index'
    get 'maps', to: 'pages#scene_overview', as: 'scene_overview'
    get 'use_cases', to: 'pages#use_cases', as: 'use_cases'
    # get 'privacy', to: 'pages#privacy', as: 'privacy'
    # get 'imprint', to: 'pages#imprint', as: 'imprint'

    resources :users

    resources :main_scenes, shallow: true do
      resources :main_scene_categories
      resources :graphical_scenes, controller: :graphical_scenes
      resources :geo_scenes, controller: :geo_scenes
      resources :users
    end

    resources :graphical_scenes, shallow: true do
      resources :scene_categories
      resources :sub_scenes do
        resources :info_buttons
      end
    end

    resources :geo_scenes, shallow: true do
      resources :scene_categories
      resources :sub_scenes do
        resources :info_buttons
      end
    end

    resources :main_scenes
    resources :graphical_scenes, controller: :graphical_scenes
    resources :geo_scenes, controller: :geo_scenes
    resources :sub_scenes
    resources :info_buttons
    resources :scene_categories
    resources :main_scene_categories
    resources :system_effect_chains
    resources :system_effects

    post 'info_buttons/create_category_marker', to: 'info_buttons#create_category_marker'
    post 'info_buttons/:id/clone', to: 'info_buttons#clone'

    get 'sub_scenes/:id/all_info_buttons', to: 'sub_scenes#all_info_buttons'

    post 'export/pdf', to: 'export#pdf'
    get 'export/pdf', to: 'export#pdf'
    get 'export/single_item_pdf', to: 'export#single_item_pdf'
    get 'export/excel',  to: 'export#excel', as: 'excel'

    get 'map/:id', to: 'main_scenes#show_on_map', as: 'main_scene_map'
    get 'map/:id/settings', to: 'main_scenes#settings', as: 'main_scene_settings'

    get 'sub/:id', to: 'graphical_scenes#show_on_map', as: 'graphical_scene_map'
    get 'sub/:id/settings', to: 'graphical_scenes#settings', as: 'graphical_scene_settings'
    get 'sub/:id/list', to: 'graphical_scenes#info_button_list', as: 'graphical_scene_list'

    get 'gmap/:id', to: 'geo_scenes#show_on_map', as: 'geo_scene_map'
    get 'gmap/:id/settings', to: 'geo_scenes#settings', as: 'geo_scene_settings'
    get 'gmap/:id/list', to: 'geo_scenes#info_button_list', as: 'geo_scene_list'
    get 'gmap/:id/changes', to: 'geo_scenes#changes', as: 'geo_scene_changes'

    get '/login' => 'sessions#new', as: 'login'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'

    post '/users' => 'users#create'

    post 'attachment/upload' => 'attachments#upload'

    get '/log', to: 'admin#log'
  end
end

app/models/user.rb
class User < InnoMapBaseModel
  has_secure_password
  validates :password, presence: true, confirmation: true, length: { minimum: 8 }, allow_nil: true

  has_many :main_scenes_users
  has_many :main_scenes, through: :main_scenes_users
  accepts_nested_attributes_for :main_scenes_users, reject_if: :all_blank, allow_destroy: true

  scope :admins, -> { where(admin: true) }

  def assign_permission_for(main_scene, edit: false, own: false)
    MainScenesUser.create(user_id: id, main_scene_id: main_scene.id, edit: edit, own: own)
  end

  def main_scenes_as_owner
    return main_scenes if admin?
    main_scenes_users.where(own: true).map(&:main_scene)
  end

  def main_scenes_as_editor
    return main_scenes if admin?
    main_scenes_users.where(edit: true).map(&:main_scene)
  end

  def owner_of?(scene)
    return true if admin?
    main_scene_id = scene.class.name == 'MainScene' ? scene.id : scene.main_scene.id
    main_scenes_users.find_by(main_scene_id: main_scene_id)&.own?
  end


  def writing_permission_for?(scene)
    return true if admin?
    main_scene_id = scene.class.name == 'MainScene' ? scene.id : scene.main_scene.id
    main_scenes_users.find_by(main_scene_id: main_scene_id)&.edit?
  end

  def reading_permission_for?(scene)
    return true if scene.public? || admin?
    main_scene = scene.class.name == 'MainScene' ? scene : scene.main_scene
    main_scenes.include?(main_scene)
  end

  def has_permission_to_destroy_user?(user)
    return true if admin?
    user.main_scenes.each do |ms|
      return false unless main_scenes.include?(ms)
    end
    return true
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_main_scene
  before_action except: [:destroy] do
    @main_scene ? assure_owner_for(@main_scene) : authorize_as_admin
  end

  def index
    @admins = @main_scene ? nil : User.admins
    @users = @main_scene ? @main_scene.users : User.all - @admins
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    in_modal_validation(@user, @user.update_attributes(user_params.except(:main_scene_id)))
    flash[:success] = "User editiert: Passwort: #{@user.password}"
  end

  def new
    @user = User.new
    @password = SecureRandom.hex(4)
  end

  def create
    @user = User.new(user_params.except(:main_scene_id))

    if @user.save && (@main_scene ? @user.assign_permission_for(@main_scene) : true)
      flash[:success] = "User erfolgreich erstellt. Passwort: #{@user.password}"
      redirect_to @main_scene ? main_scene_users_path(@main_scene) : users_path
    else
      flash.now[:danger] = @user.errors.full_messages.to_sentence
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    if current_user.has_permission_to_destroy_user?(@user)
      @user.destroy
      redirect_to :back
    else
      flash[:danger] = 'You are not allowed to do this! Propably this user has permissions for any other maps.'
      redirect_to :back
    end
  end

  private

  def find_main_scene
    main_scene_id = params[:main_scene_id] || (params[:user] && user_params[:main_scene_id])
    @main_scene = MainScene.find(main_scene_id) if main_scene_id
  end

  def user_params
    params.require(:user).permit(
      :email, :password, :password_confirmation, :main_scene_id,
      main_scenes_users_attributes: %i[id user_id main_scene_id own edit _destroy]
    )
  end
end

app/views/users/_user_form.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{"data-dismiss" => "modal", :type => "button"} ×
      %h4.modal-title= @user.email
    = form_for(@user) do |form|
      .modal-body
        .row
          .col-xs-12
            %h3 New password
          .col-xs-6
            Password:
            = form.text_field :password, value: @password
          .col-xs-6
            Password confirmation:
            = form.text_field :password_confirmation, value: @password

        .row
          .col-xs-12
            %h3 Permissions

        - if @main_scene
          = render 'user_permission_form', form: form, main_scene: @main_scene
          = form.hidden_field :main_scene_id, value: @main_scene&.id
        - else
          - MainScene.all.each do |main_scene|
            = render 'user_permission_form', form: form, main_scene: main_scene


      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
        = button_tag('Save', type: 'submit', class: 'btn btn-success')

app/views/users/_user_permission_form.html.haml
// row class mainly for testing purposes
.row{class: "main_scene_#{main_scene.id}"}
  .col-xs-6
    %b= main_scene.text
  .col-xs-6
    = form.fields_for :main_scenes_users, MainScenesUser.find_or_initialize_by(user_id: @user.id, main_scene_id: main_scene.id) do |builder|
      Visitor?
      // destroy checkbox acts as the oppsite (relation is deleted if not checked)
      = builder.check_box '_destroy', {checked: !builder.object.new_record?, class: 'read-permission-checkbox'}, '0', '1'
      Editor?
      = builder.check_box :edit, {class: 'write-permission-checkbox'}
      Owner?
      = builder.check_box :own, {class: 'owner-checkbox'}

      = builder.hidden_field :id
      = builder.hidden_field :user_id, value: @user.id
      = builder.hidden_field :main_scene_id, value: main_scene.id

app/views/users/edit.js.erb
jQuery("#form-modal").html("<%= escape_javascript(render 'users/user_form') %>").modal('show');

app/views/users/index.html.haml
= stylesheet_link_tag    'dataTables/jquery.dataTables'
= stylesheet_link_tag    'dataTables/extras/dataTables.responsive'
= javascript_include_tag 'dataTables/jquery.dataTables'
= javascript_include_tag 'dataTables/extras/dataTables.responsive'
= javascript_include_tag 'users_list'

%section
  .container.inner-xs
    .row
      .col-xs-12
        - if @main_scene
          %h1
            Users for
            = @main_scene.text
          = link_to new_main_scene_user_path do
            .btn.btn-default Create new scene user
        - else
          %h1 Users
          = link_to new_user_path do
            .btn.btn-default Create new user

    .row
      .col-xs-12
        - if @admins
          %table.users-table.display.responsive.no-wrap.compact{cellspacing: '0', width: '100%'}
            %thead
              %tr
                %th Email
                %th Created at
                %th Updated at

            %tbody
              - @admins.each do |u|
                %tr
                  %td
                    %b= 'Admin: ' + u.email
                  %td= u.created_at
                  %td= u.updated_at

        %table.users-table.display.responsive.no-wrap.compact{cellspacing: '0', width: '100%'}
          %thead
            %tr
              %th Email
              %th Created at
              %th Updated at
              %th Reader of
              %th Editor of
              %th Owner of
              %th Rights
              %th Delete

          %tbody
            - @users.each do |u|
              %tr
                %td= u.email
                %td= u.created_at
                %td= u.updated_at
                %th{title: u.main_scenes.map(&:text).join("\n")}= u.main_scenes.count
                %th{title: u.main_scenes_as_editor.map(&:text).join("\n")}= u.main_scenes_as_editor.count
                %th{title: u.main_scenes_as_owner.map(&:text).join("\n")}= u.main_scenes_as_owner.count
                %th
                  - if @main_scene
                    = link_to edit_user_path(id: u.id, main_scene_id: @main_scene.id), remote: true do
                      %i.icon-cog
                  - else
                    = link_to edit_user_path(id: u.id), remote: true do
                      %i.icon-cog
                %th
                  = link_to user_path(u.id), method: 'delete', data: { confirm: 'Do you really want to delete the user?' } do
                    %i.icon-trash-1

app/views/users/new.html.haml
%section
  .container.inner-xs
    .row
      .col-sm-6.col-sm-offset-3
        %h1 Create new user
        .row
          = form_for @user do |f|
            .col-xs-12
              Email:
              = f.text_field :email
            .col-xs-6
              Password:
              = f.text_field :password, value: @password
            .col-xs-6
              Password confirmation:
              = f.text_field :password_confirmation, value: @password
            .col-xs-12
              - if @main_scene
                = f.hidden_field :main_scene_id, value: @main_scene.id
              = f.button 'Create', class: 'btn btn-default'