config/routes.rb
# rubocop:disable Metrics/BlockLength
require_relative 'subdomains'

Rails.application.routes.draw do
  scope '(:locale)', locale: /de|en/ do
    get 'automated_driving' => 'geo_scenes#show_on_map', id: 1

    root 'pages#index'
    get 'maps', to: 'pages#scene_overview', as: 'scene_overview'
    get 'use_cases', to: 'pages#use_cases', as: 'use_cases'
    # get 'privacy', to: 'pages#privacy', as: 'privacy'
    # get 'imprint', to: 'pages#imprint', as: 'imprint'

    resources :users

    resources :main_scenes, shallow: true do
      resources :main_scene_categories
      resources :graphical_scenes, controller: :graphical_scenes
      resources :geo_scenes, controller: :geo_scenes
      resources :users
    end

    resources :graphical_scenes, shallow: true do
      resources :scene_categories
      resources :sub_scenes do
        resources :info_buttons
      end
    end

    resources :geo_scenes, shallow: true do
      resources :scene_categories
      resources :sub_scenes do
        resources :info_buttons
      end
    end

    resources :main_scenes
    resources :graphical_scenes, controller: :graphical_scenes
    resources :geo_scenes, controller: :geo_scenes
    resources :sub_scenes
    resources :info_buttons
    resources :scene_categories
    resources :main_scene_categories
    resources :system_effect_chains
    resources :system_effects

    post 'info_buttons/create_category_marker', to: 'info_buttons#create_category_marker'
    post 'info_buttons/:id/clone', to: 'info_buttons#clone'

    get 'sub_scenes/:id/all_info_buttons', to: 'sub_scenes#all_info_buttons'

    post 'export/pdf', to: 'export#pdf'
    get 'export/pdf', to: 'export#pdf'
    get 'export/single_item_pdf', to: 'export#single_item_pdf'
    get 'export/excel',  to: 'export#excel', as: 'excel'

    get 'map/:id', to: 'main_scenes#show_on_map', as: 'main_scene_map'
    get 'map/:id/settings', to: 'main_scenes#settings', as: 'main_scene_settings'

    get 'sub/:id', to: 'graphical_scenes#show_on_map', as: 'graphical_scene_map'
    get 'sub/:id/settings', to: 'graphical_scenes#settings', as: 'graphical_scene_settings'
    get 'sub/:id/list', to: 'graphical_scenes#info_button_list', as: 'graphical_scene_list'

    get 'gmap/:id', to: 'geo_scenes#show_on_map', as: 'geo_scene_map'
    get 'gmap/:id/settings', to: 'geo_scenes#settings', as: 'geo_scene_settings'
    get 'gmap/:id/list', to: 'geo_scenes#info_button_list', as: 'geo_scene_list'
    get 'gmap/:id/changes', to: 'geo_scenes#changes', as: 'geo_scene_changes'

    get '/login' => 'sessions#new', as: 'login'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'

    post '/users' => 'users#create'

    post 'attachment/upload' => 'attachments#upload'

    get '/log', to: 'admin#log'
  end
end

app/models/geo_scene.rb
class GeoScene < Scene
  def tile_layer_url
    tile_layers[tile_layer][:url]
  end

  def tile_layers
    hash = {}
    tile_layer_info.each do |k, v|
      hash[k] = v.merge(sample: url_sample_tile(v[:url]))
    end
    hash
  end

  def tile_layer_sample
    url_sample_tile(tile_layers[tile_layer][:sample])
  end

  # rubocop:disable Metrics/MethodLength
  def tile_layer_info
    {
      1 => {
        url: 'http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png',
        name: 'SimplifiedWhite',
      },
      2 => {
        url: 'http://tile.openstreetmap.org/{z}/{x}/{y}.png',
        name: 'Openstreetmap',
      },
      3 => {
        url: 'http://{s}.tile.stamen.com/watercolor/{z}/{x}/{y}.png',
        name: 'Watercolor',
      },
      4 => {
        url: 'https://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}.jpg',
        name: 'Topographic',
      },
      5 => {
        url: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}.jpg',
        name: 'Satellite',
      },
      6 => {
        url: 'https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png',
        name: 'Openstreetmap (hot)',
      }
    }
  end

  def url_sample_tile(url)
    url
      .gsub('{s}', 'a')
      .gsub('{z}', '11')
      .gsub('{x}', '596')
      .gsub('{y}', '776')
  end
end

app/controllers/geo_scenes_controller.rb
class GeoScenesController < ApplicationController
  before_action :assure_writing_permission, except: %i[index info_button_list show_on_map new create]
  before_action :assure_reading_permission, only: %i[index info_button_list show_on_map changes]
  before_action :authorize, only: %i[create new]

  def changes
    @geo_scene = GeoScene.find(params[:id])
    info_button_ids = @geo_scene.sub_scenes.first.info_buttons.map(&:id)
    versions_of_scene = PaperTrail::Version.where(item_type: 'InfoButton', item_id: info_button_ids)
    @versions = InfoButtonLog.new(versions_of_scene.order(created_at: :desc).limit(100)).hash
  end

  def show_on_map
    @geo_scene = GeoScene.find(params[:id])
    @categories = @geo_scene.scene_categories
    @welcome = @geo_scene.welcome

    respond_to do |format|
      format.html
      format.json { render json: @geo_scene.json_with_content }
    end
  end

  def index
    @geo_scenes = GeoScene.all.order(:created_at)
  end

  def settings
    @geo_scene = GeoScene.find(params[:id])
    @sub_scenes = @geo_scene.sub_scenes
    @geo_scene_categories = @geo_scene.scene_categories
  end

  def info_button_list
    @geo_scene = GeoScene.find(params[:id])
    @sub_scenes = @geo_scene.sub_scenes
    @attributes = @geo_scene.content_attributes
  end

  def new
    @main_scene = MainScene.find(main_scene_id)
    @geo_scene = @main_scene.geo_scenes.build(
      latitude: params[:latitude],
      longitude: params[:longitude]
    )
    5.times { @geo_scene.content_attributes.build }
  end

  def create
    @main_scene = MainScene.find(main_scene_id)
    @geo_scene = GeoScene.new(geo_scene_params)
    in_modal_validation(@geo_scene, validate_content_attributes && @geo_scene.save)
  end

  def edit
    @geo_scene = GeoScene.find(params[:id])
    5.times { @geo_scene.content_attributes.build }
  end

  def update
    @geo_scene = GeoScene.find(params[:id])
    in_modal_validation(@geo_scene, validate_content_attributes && @geo_scene.update_attributes(geo_scene_params) && delete_if_empty)
  end

  def destroy
    @geo_scene = GeoScene.find(params[:id])
    @geo_scene.destroy
    respond_to do |format|
      format.json { render json: nil, status: :ok }
      format.html { redirect_to scene_overview_path }
    end
  end

  private

  def main_scene_id
    if params[:id]
      Scene.find(params[:id]).main_scene_id
    else
      params[:main_scene_id] || geo_scene_params[:main_scene_id]
    end
  end

  def delete_if_empty
    @geo_scene.content_attributes.where(name: '').destroy_all
  end

  def assure_reading_permission
    assure_reading_permission_for(GeoScene.find(params[:id]))
  end

  def assure_writing_permission
    assure_writing_permission_for(GeoScene.find(params[:id]))
  end

  def geo_scene_params
    params.require(:geo_scene).permit(
      :main_scene_id,
      :text,
      :welcome,
      :latitude,
      :longitude,
      :tile_layer,
      :public_contributions_allowed,
      :public,
      content_attributes_attributes: %i[id name info position options]
    )
  end
end

app/views/geo_scenes/_form.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{"data-dismiss" => "modal", :type => "button"} ×
      %h4.modal-title Geographic map
    = form_for(@geo_scene, remote: params[:remote]) do |f|
      .modal-body
        .row.margin-below
          .col-xs-12
            = f.text_field :text, placeholder: 'Name', class: 'form-control'
        .row.margin-below
          %b.col-xs-12
            Coordinates
          .col-xs-6
            = f.text_field :longitude, placeholder: 'x-coordinate', class: 'form-control'
          .col-xs-6
            = f.text_field :latitude, placeholder: 'y-coordinate', class: 'form-control'
        .row.margin-below
          %b.col-xs-12
            Welcome window
          .col-xs-12
            = f.text_area :welcome, placeholder: t('welcome_window'), class: 'form-control froala'


        .row
          %b.col-xs-12
            Attributes
          %p.col-xs-12
            If the info button contents should have a specific structure, set field names here. The fields will be ordered by the positioning number. If no position is set explicitly, new fields are appended to the bottom. Use the keyword 'HTML' anywhere in the field name to provide an HTML editor to the user for this field.
          .col-xs-12
            = f.fields_for :content_attributes do |builder|
              .row.margin-below
                .col-xs-3
                  = builder.text_field :position, placeholder: 'Position', class: 'form-control'
                .col-xs-9
                  = builder.text_field :info, placeholder: 'User info text', class: 'form-control'
                .col-xs-6
                  = builder.text_field :name, placeholder: 'Attribute', class: 'form-control'
                .col-xs-6
                  = builder.text_field :options, placeholder: 'Options for dropdown', class: 'form-control'

        .row
          %b.col-xs-12
            Background map
          .col-xs-12.geo-scene-tile-dropdown
            = f.select(:tile_layer, @geo_scene.tile_layers.map{ |k, v| [v[:name], k, title: v[:sample]] }, {}, class: 'image-dropown')
        .row
          .col-xs-12
            .checkbox
              %label
                = f.check_box :public_contributions_allowed
                allow public contributions?
            .checkbox
              %label
                = f.check_box :public
                public?

        - if @main_scene
          = f.hidden_field :main_scene_id, value: @main_scene.id

      .modal-footer
        %button.btn.btn-default{'data-dismiss' => 'modal', type: 'button'} Close
        = button_tag('Save', type: 'submit', class: 'btn btn-success')

app/views/geo_scenes/changes.html.haml
.container#changes.inner-xs
  %h2 Change log
  .row
    .col-xs-12
      - @versions.each do |version|
        .inner-bottom-xs
          %h3= version['name']
          - if version['changes'].present?
            .row.attribute-row
              %b.col-xs-4 Attribute name
              %b.col-xs-4 from
              %b.col-xs-4 to
            - version['changes'].each do |key, value|
              .row.attribute-row
                .col-xs-4= key
                .col-xs-4= value[0]
                .col-xs-4= value[1]
          - else
            created

app/views/geo_scenes/edit.js.erb
jQuery("#form-modal").html("<%= escape_javascript(render 'geo_scenes/form') %>").modal('show');

app/views/geo_scenes/info_button_list.html.haml
.container.inner-xs
  .row
    .col-xs-12
      = render 'info_button_list'

app/views/geo_scenes/new.js.erb
jQuery("#form-modal").html("<%= escape_javascript(render 'geo_scenes/form') %>").modal('show');

app/views/geo_scenes/settings.html.haml
%section
  .container
    .row.inner-top-xs.inner-bottom-sm
      .col-xs-12
        .tabs.tabs-top.tab-container
          %ul.etabs.text-center
            - if user_has_writing_permission
              %li.tab
                = link_to "Config", "#2-tab"
              %li.tab
                = link_to "Categories", "#3-tab"

          - if user_has_writing_permission
            .panel-container
              .tab-content#2-tab
                .row
                .col-xs-12
                %h1= @geo_scene.text
                %h4= link_to 'Change configuration', edit_geo_scene_path(@geo_scene), remote: true
                .col-xs-12
                %h4= link_to 'Delete map', geo_scene_path(@geo_scene.id), method: 'delete', data: { confirm: 'Do you really want to delete this with all the content?' }

            .panel-container
              .tab-content#3-tab
                .row
                  .col-xs-12
                    %h2 Map categories
                    = link_to new_geo_scene_scene_category_path(@geo_scene.id), remote: true do
                      %h4 Assign a category to this map
                  - @geo_scene_categories.in_groups_of(4, false) do |group|
                    - group.each do |scene_category|
                      .col-xs-6.col-md-3
                        .list-element.high-list-element
                          .list-title
                            %h4
                              = scene_category.name
                            = link_to edit_scene_category_path(scene_category.id, geo_scene_id: @geo_scene.id), remote: true do
                              %i.icon-pencil-1
                            = link_to scene_category_path(scene_category.id, geo_scene_id: @geo_scene.id), method: 'delete', data: { confirm: 'Do you really want to delete this?' } do
                              %i.icon-trash-1
                            -# %b= Category.find(scene_category.category_id).name
                          - if scene_category.icon.url.present?
                            = image_tag(scene_category.icon, width: '100%')
                          - else
                            %br
                            No image uploaded

app/views/geo_scenes/show_on_map.html.haml
= render 'map'

#geocoder-modal.modal{:role => "dialog"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"} ×
        %h4.modal-title
          Search city or address
      .modal-body
        .row
          .col-xs-12.geocoder-container


= javascript_include_tag 'geo_scene.js'

- if @welcome.present?
  = render 'welcome_modal'

:javascript
  window.sceneName = '#{@geo_scene.text}';
  window.currentGeoSceneId = #{@geo_scene.id};
  window.categoriesActive = true;
  window.tileLayerUrl = '#{@geo_scene.tile_layer_url}';